### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by ITS-Marcelo** [OpenHero/gblastn#11]
I'm using the latest version (https://github.com/OpenHero/gblastn/commit/f31125a18a0b7b42591404954657972f67c74f67) of gblastn and followed the README:

First I did:
`configure --without-debug --with-mt --without-sybase --without-fastcgi --without-sssdb --without-sss --without-geo --without-sp --without-orbacus --without-boost`

The configure step ended with this message:
>******* CONFIGURATION SUCCESSFUL *******

Then:
`make`

The make steps exits on an error:
> make[3]: *** [/home/protedex/gblastn/c++/GCC900-ReleaseMT64/build/Makefile.rules:26: blob_storage.o] Error 1
make[3]: Leaving directory '/home/protedex/gblastn/c++/GCC900-ReleaseMT64/build/corelib'
FAILED: src/corelib/Makefile.corelib.lib
make[3]: Entering directory '/home/protedex/gblastn/c++/GCC900-ReleaseMT64/build/corelib'
/bin/rm -f libxncbi.a .xncbi.dep .libxncbi.a.stamp
/bin/rm -f /home/protedex/gblastn/c++/GCC900-ReleaseMT64/lib/libxncbi.a /home/protedex/gblastn/c++/GCC900-ReleaseMT64/status/.xncbi.dep \
    /home/protedex/gblastn/c++/GCC900-ReleaseMT64/lib/libxncbi-static.a /home/protedex/gblastn/c++/GCC900-ReleaseMT64/status/.xncbi-static.dep
make[3]: Leaving directory '/home/protedex/gblastn/c++/GCC900-ReleaseMT64/build/corelib'
make[2]: *** [/home/protedex/gblastn/c++/src/build-system/Makefile.meta_l:240: all.nonusr] Error 2
make[2]: Leaving directory '/home/protedex/gblastn/c++/GCC900-ReleaseMT64/build/corelib'
make[1]: *** [/home/protedex/gblastn/c++/src/build-system/Makefile.meta_r:41: all_r.real] Error 5
make[1]: Leaving directory '/home/protedex/gblastn/c++/GCC900-ReleaseMT64/build'
make: *** [Makefile:23: all] Error 2

Any suggestions on fixing the issue would be appreciated.

**Comment by OpenHero** [comment]
which OS ? I have test with Ubuntu 18.04 and 20.04.

**Comment by zoomlion** [comment]
Also Ubuntu 1804, maybe the some minor mistake of source code? =-(



Best wishes, 
From ***@***.***
 
From: kyzhao
Date: 2022-10-20 10:01
To: OpenHero/gblastn
CC: Zheng; Comment
Subject: Re: [OpenHero/gblastn] Compilation error (Issue #11)
which OS ? I have test with Ubuntu 18.04 and 20.04.

**Comment by OpenHero** [comment]
fixed this bug with new commit https://github.com/OpenHero/gblastn/commit/1f931d5910150f44e8ceab81599428027703c879
