### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by jusjusjus** [OpenHero/gblastn#3]
System:  Ubuntu 14.04
Cuda compilation tools, release 5.5, V5.5.0.
They are installed via apt-get, which is possible since 14.

Error msg; 

> Compiling CUDA code
> /home/jus/Code/gpu_blast/ncbi-blast-2.2.28+-src/c++/src/algo/blast/gpu_blast/
> .cuda_bin_dir /usr/bin
> cuda_dir /usr
> CUDA library directory cannot be found. Exiting installation...

Script 'install' looks for /usr/lib64, but in a generic x86_64, it's either
/usr/lib or /usr/lib32.

One needs to find a better way to determine the cuda install path.

**Comment by aubreybailey** [comment]
seconded.
I hacked at this for a bit. made it compile, mostly. Checked the old version of blast that this work on... switched to barracuda tools

**Comment by OpenHero** [comment]
please use new version
