### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by kedougan** [OpenHero/gblastn#4]
It seems as though the installation is not completing properly but I'm not getting an error message. Below is the output to the terminal:

Do you want to install GPU-BLASTN on an existing installation of "blastn" [yes/no]
yes: you will be asked for the installation directory of the "blastn" executable
no: will download and install "ncbi-blast-2.2.28+-src"
yes
Please input the bin directory of "blastn" of "ncbi-blast-2.2.28+-src"
e.g.: /ssd/blast/src/ncbi-blast-2.2.28+-src/c++/GCC447-ReleaseMT64/bin
/home/vader/apps/ncbi-blast-2.2.28+-src/c++/GCC480-ReleaseMT64/bin
"blastn" version 2.2.28+ is compatible
Continuing with the installation of GPU-BLASTN...
Building NCBI BLAST with BLAST
................................
/home/vader/apps/ncbi-blast-2.2.28+-src/c++/GCC480-ReleaseMT64/bin/../../

Modifying NCBI BLAST files
/home/vader/apps/gblastn
cd /home/vader/apps/ncbi-blast-2.2.28+-src/c++/GCC480-ReleaseMT64/bin/../..//src/algo/blast/gpu_blast/

Compiling CUDA code
/home/vader/apps/ncbi-blast-2.2.28+-src/c++/GCC480-ReleaseMT64/bin/../..//src/algo/blast/gpu_blast/
.cuda_bin_dir /usr/local/cuda-8.0/bin
cuda_dir /usr/local/cuda-8.0
Completed compiled gpu part......

Building NCBI BLAST with GPU BLAST
................................

But then in the gpu_blast.output log file I have this:

make: makefile: No such file or directory
make: *** No rule to make target 'makefile'.  Stop.

**Comment by OpenHero** [comment]
Please use the new version
