### ISSUE TITLE
configure error on powerpc architecture

### ISSUE THREAD

**Issue by ketancmaheshwari** [OpenHero/gblastn#5]
I am getting configure errors on powerpc architecture when trying to configure with the flags provided. Here is the command and the detailed output:

`$ ./configure --without-debug --with-mt --without-sybase --without-fastcgi --without-sssdb --without-sss --without-geo --without-sp --without-orbacus --without-boost --prefix=/ccs/home/ketan2/summitwork/gblastn/install
configure: loading site script ./src/build-system/config.site

configure: creating cache config.cache
checking build system type... src/build-system/config.guess: unable to guess system type

This script, last modified 2003-02-22, has failed to recognize
the operating system you are using. It is advised that you
download the most up to date version of the config scripts from

    ftp://ftp.gnu.org/pub/gnu/config/

If the version you run (src/build-system/config.guess) is already up to date, please
send the following data and any information you think might be
pertinent to <config-patches@gnu.org> in order to provide the needed
information to handle your system.

config.guess timestamp = 2003-02-22

uname -m = ppc64le
uname -r = 4.14.0-115.8.1.el7a.ppc64le
uname -s = Linux
uname -v = #1 SMP Thu May 9 14:45:13 UTC 2019

/usr/bin/uname -p = ppc64le
/bin/uname -X     =

hostinfo               =
/bin/universe          =
/usr/bin/arch -k       =
/bin/arch              = ppc64le
/usr/bin/oslevel       =
/usr/convex/getsysinfo =

UNAME_MACHINE = ppc64le
UNAME_RELEASE = 4.14.0-115.8.1.el7a.ppc64le
UNAME_SYSTEM  = Linux
UNAME_VERSION = #1 SMP Thu May 9 14:45:13 UTC 2019
configure: error: cannot guess build type; you must specify one`

**Comment by OpenHero** [comment]
Plz try the new commit.
