### ISSUE TITLE
Update Versions

### ISSUE THREAD

**Issue by dorton21** [OpenHero/gblastn#9]
Many commits have been added since the last version release 7 years ago. Perhaps it is time for version 1.2 to be released?

**Comment by dorton21** [comment]
The LAS research team uses this repo. It would be awesome if we could get an updated tar.gz released.

**Comment by OpenHero** [comment]
So you need a tar.gz file? Could you tell me your configuration of the system? And also,you can clone it:)

**Comment by dorton21** [comment]
It's not so much the tar.gz file as it is having a new version in releases. We build packages for the spack framework and having the latest version in releases allows us to grab new and old versions automatically. Right now we are using the tarball that can be extracted from commits but this means we have to manually add each version. Spack strives to be used on any system so whatever Linux system you use will work.

**Comment by OpenHero** [comment]
> It's not so much the tar.gz file as it is having a new version in releases. We build packages for the spack framework and having the latest version in releases allows us to grab new and old versions automatically. Right now we are using the tarball that can be extracted from commits but this means we have to manually add each version. Spack strives to be used on any system so whatever Linux system you use will work.

  CUDA 10.1 Ubuntu 18.x GCC 7.x

**Comment by OpenHero** [comment]
I see. Done～
